from app.core.types import RoleNames

from .permission_types import Permissions

user_crud: list[Permissions] = ["user:create", "user:update", "user:delete", "user:read"]


product_crud: list[Permissions] = [
    "product-category:create",
    "product-category:read",
    "product-category:update",
    "product-category:delete",
    "product:create",
    "product:read",
    "product:update",
    "product:delete",
]

partner_organization_permissions: list[Permissions] = [
    "partner-organization:read",
    "partner-organization:create",
    "partner-organization:update",
    "partner-organization:delete",
]


advisor_permissions: list[Permissions] = [
    "appointment:create",
    "appointment:read",
    "appointment:update",
    "appointment:delete",
    "appointment:update:status",
    "appointment:update:date",
    "appointment:form:update-checkgesprek",
    "appointment:form:update-toekomstgesprek",
    "appointment:file:update",
    "appointment:file:delete",
    "appointment:file:create",
    "appointment:file:read",
    "availability:create",
    "availability:read",
    "availability:update",
    "availability:delete",
    "case:create",
    "case:read",
    "case:update",
    "case:delete",
    "task:read",
    "task:update",
    "task:create",
    "task:delete",
    "task:update:case",
    "task:update:completion-status",
    "case:file:update",
    "case:file:create",
    "case:file:delete",
    "case:file:read",
    "client:create",
    "client:read",
    "client:update",
    "client:delete",
    "comment:read",
    "comment:create",
    "form:create",
    "form:read",
    "form:read-all",
    "form:update",
    "form:approve",
    "role:create",
    "role:read",
    "role:update",
    "role:delete",
    "request:create",
    "request:read",
    "request:update",
    "request:delete",
    "track:create",
    "track:read",
    "track:update",
    "track:update:status",
    "track:update:partner",
    "track:update:product-category",
    "track:update:completion_approval",
    "track:update:product",
    "track:form:update-eindevaluatie-adviseur",
    "track:form:update-eindevaluatie-partnerorganisatie",
    "track:form:update-volggesprek",
    "track:send-notification:partner-request",
    "track:file:create",
    "track:file:update",
    "track:file:delete",
    "track:file:read",
    "track:delete",
    "user-basic:read",
]

all_permissions = (
    advisor_permissions + user_crud + partner_organization_permissions + ["client:create-user"] + product_crud
)


role_permissions: dict[RoleNames, list[Permissions]] = {
    "beheerder": all_permissions,
    "adviseur": advisor_permissions + ["partner-organization:read"] + product_crud,
    "senioradviseur": advisor_permissions + ["user:delete"] + partner_organization_permissions,
    "partner": [
        "case:read",
        "client:read",
        "track:update:completion_approval",
        "track:update:status",
        "track:update:product",
        "track:read",
        "form:read",
        "form:create",
        "track:form:update-eindevaluatie-partnerorganisatie",
        "track:form:update-volggesprek",
        "track:file:update",
        "track:file:create",
        "track:file:read",
        "track:file:delete",
        "track:update:product",
        "form:update",
        "appointment:form:update-toekomstgesprek",
        "appointment:read",
        "appointment:update:date",
        "appointment:update:status",
        "appointment:file:create",
        "appointment:file:update",
        "appointment:file:read",
        "appointment:file:delete",
        "task:read",
        "task:update:completion-status",
        "product:read",
        "user-basic:read",
    ],
    "ondernemer": [
        "case:read",
        "case:file:read",
        "form:read",
        "client:read",
        "case:file:create",
        "case:file:delete",
        "partner-organization:read",
        "user-basic:read",
        "task:read",
        "task:update:completion-status",
        "appointment:read",
        "track:read",
        "request:read",
        "form:update",
        "request:update",
    ],
}
