/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue')['EffectScope']
  const computed: typeof import('vue')['computed']
  const createApp: typeof import('vue')['createApp']
  const customRef: typeof import('vue')['customRef']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineComponent: typeof import('vue')['defineComponent']
  const effectScope: typeof import('vue')['effectScope']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const h: typeof import('vue')['h']
  const handleLogin: typeof import('./src/composables/useKeycloak')['handleLogin']
  const inject: typeof import('vue')['inject']
  const isProxy: typeof import('vue')['isProxy']
  const isReactive: typeof import('vue')['isReactive']
  const isReadonly: typeof import('vue')['isReadonly']
  const isRef: typeof import('vue')['isRef']
  const markRaw: typeof import('vue')['markRaw']
  const nextTick: typeof import('vue')['nextTick']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeRouteLeave: typeof import('vue-router')['onBeforeRouteLeave']
  const onBeforeRouteUpdate: typeof import('vue-router')['onBeforeRouteUpdate']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onErrorCaptured: typeof import('vue')['onErrorCaptured']
  const onMounted: typeof import('vue')['onMounted']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const onWatcherCleanup: typeof import('vue')['onWatcherCleanup']
  const provide: typeof import('vue')['provide']
  const reactive: typeof import('vue')['reactive']
  const readonly: typeof import('vue')['readonly']
  const ref: typeof import('vue')['ref']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const shallowRef: typeof import('vue')['shallowRef']
  const toRaw: typeof import('vue')['toRaw']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const toValue: typeof import('vue')['toValue']
  const triggerRef: typeof import('vue')['triggerRef']
  const unref: typeof import('vue')['unref']
  const useApiClient: typeof import('./src/composables/useApiClient')['useApiClient']
  const useAppointment: typeof import('./src/composables/useAppointment')['useAppointment']
  const useAppointments: typeof import('./src/composables/useAppointments')['useAppointments']
  const useAttrs: typeof import('vue')['useAttrs']
  const useAuth: typeof import('./src/composables/useAuth')['useAuth']
  const useAvailability: typeof import('./src/composables/useAvailability')['useAvailability']
  const useCase: typeof import('./src/composables/useCase')['useCase']
  const useClient: typeof import('./src/composables/useClient')['useClient']
  const useComment: typeof import('./src/composables/useComment')['useComment']
  const useConfig: typeof import('./src/composables/useConfig')['useConfig']
  const useConfirm: typeof import('./src/composables/useConfirm')['useConfirm']
  const useCssModule: typeof import('vue')['useCssModule']
  const useCssVars: typeof import('vue')['useCssVars']
  const useEntityLabels: typeof import('./src/composables/useEntityLabels')['useEntityLabels']
  const useFile: typeof import('./src/composables/useFile')['useFile']
  const useFormData: typeof import('./src/composables/useFormData')['useFormData']
  const useFormTemplate: typeof import('./src/composables/useFormTemplate')['useFormTemplate']
  const useFormValidation: typeof import('./src/composables/useFormValidation')['useFormValidation']
  const useForms: typeof import('./src/composables/useForms')['useForms']
  const useI18n: typeof import('vue-i18n')['useI18n']
  const useId: typeof import('vue')['useId']
  const useJsonSchemaValidation: typeof import('./src/composables/useJsonSchemaValidation')['useJsonSchemaValidation']
  const useKeycloak: typeof import('./src/composables/useKeycloak')['useKeycloak']
  const useLink: typeof import('vue-router')['useLink']
  const useLocale: typeof import('./src/composables/useLocale')['useLocale']
  const useModel: typeof import('vue')['useModel']
  const useNotification: typeof import('./src/composables/useNotification')['useNotification']
  const useParentRoute: typeof import('./src/composables/useParentRoute')['useParentRoute']
  const usePartnerOrganization: typeof import('./src/composables/usePartnerOrganization')['usePartnerOrganization']
  const useProduct: typeof import('./src/composables/useProduct')['useProduct']
  const useProductCategory: typeof import('./src/composables/useProductCategory')['useProductCategory']
  const useRequest: typeof import('./src/composables/useRequest')['useRequest']
  const useResponsive: typeof import('./src/composables/useResponsive')['useResponsive']
  const useRole: typeof import('./src/composables/useRole')['useRole']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  const useSlots: typeof import('vue')['useSlots']
  const useTask: typeof import('./src/composables/useTask')['useTask']
  const useTemplateRef: typeof import('vue')['useTemplateRef']
  const useTrack: typeof import('./src/composables/useTrack')['useTrack']
  const useTrackValue: typeof import('./src/composables/useTrackValue')['useTrackValue']
  const useUser: typeof import('./src/composables/useUser')['useUser']
  const useUserBasic: typeof import('./src/composables/useUserBasic')['useUserBasic']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  const watchPostEffect: typeof import('vue')['watchPostEffect']
  const watchSyncEffect: typeof import('vue')['watchSyncEffect']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { Notification } from './src/composables/useNotification'
  import('./src/composables/useNotification')
  // @ts-ignore
  export type { CommentCrudProps } from './src/views/CommentCrud.vue'
  import('./src/views/CommentCrud.vue')
  // @ts-ignore
  export type { FileTableProps } from './src/views/FileCrud.vue'
  import('./src/views/FileCrud.vue')
}
