"""remove unique constraint

Revision ID: 00a32435c3b4
Revises: bcffda693254
Create Date: 2025-07-03 16:49:55.523983

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00a32435c3b4"
down_revision: Union[str, None] = "bcffda693254"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_hour_start_hour_end_case_id", "appointment", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_hour_start_hour_end_case_id",
        "appointment",
        ["start_time", "end_time", "case_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
