"""Fix cascading

Revision ID: 0e105bb5ac65
Revises: a3f456ed9a66
Create Date: 2025-07-23 15:11:27.767079

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e105bb5ac65"
down_revision: Union[str, None] = "a3f456ed9a66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("file_approved_by_user_id_fkey", "file", type_="foreignkey")
    op.create_foreign_key(
        "file_approved_by_user_id_fkey", "file", "user", ["approved_by_user_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_constraint("form_data_last_updated_by_user_id_fkey", "form_data", type_="foreignkey")
    op.create_foreign_key(
        "form_data_last_updated_by_user_id_fkey",
        "form_data",
        "user",
        ["last_updated_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint("track_product_id_fkey", "track", type_="foreignkey")
    op.create_foreign_key("track_product_id_fkey", "track", "product", ["product_id"], ["id"], ondelete="SET NULL")
    op.drop_constraint("fk_user_role", "user", type_="foreignkey")
    op.drop_constraint("user_partner_organization_id_fkey", "user", type_="foreignkey")
    op.create_foreign_key(
        "user_partner_organization_id_fkey",
        "user",
        "partner_organization",
        ["partner_organization_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key("fk_user_role", "user", "role", ["role_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_partner_organization_id_fkey", "user", type_="foreignkey")
    op.create_foreign_key(
        "user_partner_organization_id_fkey",
        "user",
        "partner_organization",
        ["partner_organization_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.drop_constraint("fk_user_role", "user", type_="foreignkey")
    op.create_foreign_key("fk_user_role", "user", "role", ["role_id"], ["id"], ondelete="CASCADE")

    op.drop_constraint("track_product_id_fkey", "track", type_="foreignkey")
    op.create_foreign_key("track_product_id_fkey", "track", "product", ["product_id"], ["id"], ondelete="CASCADE")

    op.drop_constraint("form_data_last_updated_by_user_id_fkey", "form_data", type_="foreignkey")
    op.create_foreign_key(
        "form_data_last_updated_by_user_id_fkey",
        "form_data",
        "user",
        ["last_updated_by_user_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.drop_constraint("file_approved_by_user_id_fkey", "file", type_="foreignkey")
    op.create_foreign_key(
        "file_approved_by_user_id_fkey", "file", "user", ["approved_by_user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###
