"""availability

Revision ID: 18fe960cf1ab
Revises: 9d5666160913
Create Date: 2025-04-29 10:23:21.109191

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18fe960cf1ab"
down_revision: Union[str, None] = "9d5666160913"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "availability_dated",
        sa.Column("default", sa.Boolean(), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
    )
    op.create_table(
        "availability_slot",
        sa.Column("hour_start", sa.Integer(), nullable=False),
        sa.Column("hour_end", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hour_end"),
        sa.UniqueConstraint("hour_start"),
        sa.UniqueConstraint("hour_start", "hour_end", name="uq_hour_start_hour_end"),
    )
    op.create_table(
        "availability_slot_defined",
        sa.Column("availability_slot_id", sa.UUID(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("availability_dated_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["availability_dated_id"], ["availability_dated.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["availability_slot_id"], ["availability_slot.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "availability_slot_id", "availability_dated_id", name="uq_availability_slot_id_availability_dated_id"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("availability_slot_defined")
    op.drop_table("availability_slot")
    op.drop_table("availability_dated")
    # ### end Alembic commands ###
