"""track completion

Revision ID: 24250a7036a5
Revises: 5fb3a80273df
Create Date: 2025-05-15 09:43:50.268352

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24250a7036a5"
down_revision: Union[str, None] = "5fb3a80273df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("track", sa.Column("completion_cause", sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("track", "completion_cause")
    # ### end Alembic commands ###
