"""appointment status

Revision ID: 24f8c8910eea
Revises: 81531f682425
Create Date: 2025-06-17 13:57:46.638570

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24f8c8910eea"
down_revision: Union[str, None] = "81531f682425"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("appointment", sa.Column("status", sa.VARCHAR(length=256), nullable=True))
    op.execute("update appointment set status='Open' where status is null")
    op.alter_column("appointment", "status", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("appointment", "status")
    # ### end Alembic commands ###
