"""Track product

Revision ID: 299a4666c59b
Revises: 55daed29d06a
Create Date: 2025-07-17 11:26:45.449593

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "299a4666c59b"
down_revision: Union[str, None] = "55daed29d06a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("track", sa.Column("product_id", sa.UUID(), nullable=True))
    op.create_foreign_key("track_product_id_fkey", "track", "product", ["product_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("track_product_id_fkey", "track", type_="foreignkey")
    op.drop_column("track", "product_id")
    # ### end Alembic commands ###
