"""file approval

Revision ID: 2a07c7e36e42
Revises: 3d9fb507bfa5
Create Date: 2025-06-20 10:32:10.328355

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a07c7e36e42"
down_revision: Union[str, None] = "3d9fb507bfa5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("file_type", sa.VARCHAR(length=256), nullable=False))
    op.add_column("file", sa.Column("uploaded_by_user_id", sa.UUID(), nullable=True))
    op.add_column("file", sa.Column("approved_by_user_id", sa.UUID(), nullable=True))
    op.add_column("file", sa.Column("approved", sa.Boolean(), server_default="false", nullable=False))
    op.add_column(
        "file", sa.Column("approved_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )
    op.create_foreign_key(
        "file_approved_by_user_id_fkey", "file", "user", ["approved_by_user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "file_uploaded_by_user_id_fkey", "file", "user", ["uploaded_by_user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("file_approved_by_user_id_fkey", "file", type_="foreignkey")
    op.drop_constraint("file_uploaded_by_user_id_fkey", "file", type_="foreignkey")
    op.drop_column("file", "approved_at")
    op.drop_column("file", "approved")
    op.drop_column("file", "approved_by_user_id")
    op.drop_column("file", "uploaded_by_user_id")
    op.drop_column("file", "file_type")
    # ### end Alembic commands ###
