"""Remove unique constraint

Revision ID: 333135d3fa60
Revises: 299a4666c59b
Create Date: 2025-07-17 11:38:31.937835

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "333135d3fa60"
down_revision: Union[str, None] = "299a4666c59b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("case_task_description_key", "case_task", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "case_task_description_key", "case_task", ["description"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
