"""request form

Revision ID: 335b22557100
Revises: 5771c3de15b8
Create Date: 2025-08-07 15:40:15.117169

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "335b22557100"
down_revision: Union[str, None] = "5771c3de15b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form_data", sa.Column("request_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "form_data_request_id_fkey", "form_data", "request", ["request_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("request_form_data_id_fkey", "request", type_="foreignkey")
    op.drop_column("request", "form_data_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("request", sa.Column("form_data_id", sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(
        "request_form_data_id_fkey", "request", "form_data", ["form_data_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("form_data_request_id_fkey", "form_data", type_="foreignkey")
    op.drop_column("form_data", "request_id")
    # ### end Alembic commands ###
