"""appointment file

Revision ID: 36de56afad64
Revises: 24f8c8910eea
Create Date: 2025-06-19 10:30:31.144798

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36de56afad64"
down_revision: Union[str, None] = "24f8c8910eea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("appointment_id", sa.UUID(), nullable=True))
    op.create_unique_constraint("uq_appointment_filename", "file", ["appointment_id", "filename"])
    op.create_foreign_key(
        "file_appointment_id_fkey", "file", "appointment", ["appointment_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("file_appointment_id_fkey", "file", type_="foreignkey")
    op.drop_constraint("uq_appointment_filename", "file", type_="unique")
    op.drop_column("file", "appointment_id")
    # ### end Alembic commands ###
