"""add case table

Revision ID: 374cd42f7e11
Revises: 5c4ac4fb09af
Create Date: 2025-05-06 14:57:37.424271

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "374cd42f7e11"
down_revision: Union[str, None] = "5c4ac4fb09af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("advisor_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["advisor_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["client_id"], ["client.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("appointment", sa.Column("case_id", sa.UUID(), nullable=False))
    op.drop_constraint("uq_hour_start_hour_end_client_id", "appointment", type_="unique")
    op.create_unique_constraint("uq_hour_start_hour_end_case_id", "appointment", ["start_time", "end_time", "case_id"])
    op.drop_constraint("fk_appointment_client", "appointment", type_="foreignkey")
    op.create_foreign_key("fk_appointment_case", "appointment", "case", ["case_id"], ["id"], ondelete="CASCADE")
    op.drop_column("appointment", "client_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("appointment", sa.Column("client_id", sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint("fk_appointment_case", "appointment", type_="foreignkey")
    op.create_foreign_key("fk_appointment_client", "appointment", "client", ["client_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint("uq_hour_start_hour_end_case_id", "appointment", type_="unique")
    op.create_unique_constraint(
        "uq_hour_start_hour_end_client_id", "appointment", ["start_time", "end_time", "client_id"]
    )
    op.drop_column("appointment", "case_id")
    op.drop_table("case")
    # ### end Alembic commands ###
