"""track priority

Revision ID: 3d9fb507bfa5
Revises: 94cb9fddb440
Create Date: 2025-06-20 09:22:38.471640

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d9fb507bfa5"
down_revision: Union[str, None] = "94cb9fddb440"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("track", sa.Column("priority", sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("track", "priority")
    # ### end Alembic commands ###
