"""Formulieren in kunnen dienen

Revision ID: 416ddd4aa931
Revises: 2054237371ce
Create Date: 2025-10-17 11:36:03.431404

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "416ddd4aa931"
down_revision: Union[str, None] = "2054237371ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form_data", sa.Column("submitted", sa.Boolean(), server_default="false", nullable=False))
    op.add_column(
        "form_data",
        sa.Column("submitted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_data", "submitted_at")
    op.drop_column("form_data", "submitted")
    # ### end Alembic commands ###
