"""request enums

Revision ID: 42c653a43970
Revises: 335b22557100
Create Date: 2025-08-08 15:08:26.815912

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42c653a43970"
down_revision: Union[str, None] = "335b22557100"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "request",
        "name",
        existing_type=postgresql.ENUM("IOAZ", "BBZ", name="requestname"),
        type_=sa.VARCHAR(length=256),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "request",
        "name",
        existing_type=sa.VARCHAR(length=256),
        type_=postgresql.ENUM("IOAZ", "BBZ", name="requestname"),
        existing_nullable=False,
        postgresql_using="name::requestname",
    )
    # ### end Alembic commands ###
