"""appointment

Revision ID: 50d0c3a0b3f8
Revises: 48acfe723eeb
Create Date: 2025-04-23 12:20:08.822255

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50d0c3a0b3f8"
down_revision: Union[str, None] = "48acfe723eeb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appointment",
        sa.Column("initials", sa.VARCHAR(length=256), nullable=False),
        sa.Column("last_name_prefix", sa.VARCHAR(length=256), nullable=True),
        sa.Column("last_name", sa.VARCHAR(length=256), nullable=False),
        sa.Column("company_location", sa.VARCHAR(length=256), nullable=False),
        sa.Column("residence_location", sa.VARCHAR(length=256), nullable=False),
        sa.Column("company_name", sa.VARCHAR(length=256), nullable=False),
        sa.Column("kvk_number", sa.VARCHAR(length=256), nullable=False),
        sa.Column("phone_number", sa.VARCHAR(length=256), nullable=False),
        sa.Column("agree_to_share_data", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("appointment")
    # ### end Alembic commands ###
