"""case number

Revision ID: 525df381c604
Revises: 4c5f29f7c30e
Create Date: 2025-06-03 14:46:30.342202

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "525df381c604"
down_revision: Union[str, None] = "4c5f29f7c30e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "case", sa.Column("case_number", sa.Integer(), sa.Identity(always=False, start=200, cycle=True), nullable=False)
    )
    op.create_unique_constraint("uq_case_case_number", "case", ["case_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_case_case_number", "case", type_="unique")
    op.drop_column("case", "case_number")
    # ### end Alembic commands ###
