"""track form

Revision ID: 5390a0862f31
Revises: 8708826607cd
Create Date: 2025-05-30 10:40:46.905226

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5390a0862f31"
down_revision: Union[str, None] = "8708826607cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "form_track",
        sa.Column("track_id", sa.UUID(), nullable=True),
        sa.Column("form_data_Id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["form_data_Id"],
            ["form_data.id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["track.id"],
        ),
    )
    op.drop_constraint("track_form_data_id_fkey", "track", type_="foreignkey")
    op.drop_column("track", "form_data_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("track", sa.Column("form_data_id", sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key("track_form_data_id_fkey", "track", "form_data", ["form_data_id"], ["id"], ondelete="CASCADE")
    op.drop_table("form_track")
    # ### end Alembic commands ###
