"""request

Revision ID: 5771c3de15b8
Revises: 6d2ca8633040
Create Date: 2025-08-07 15:18:08.790224

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5771c3de15b8"
down_revision: Union[str, None] = "6d2ca8633040"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("request", sa.Column("form_data_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        "request_form_data_id_fkey", "request", "form_data", ["form_data_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("request_form_data_id_fkey", "request", type_="foreignkey")
    op.drop_column("request", "form_data_id")
    # ### end Alembic commands ###
