"""kvk and company nullable

Revision ID: 5850b285a8b5
Revises: b4a089bf66a9
Create Date: 2025-05-13 11:39:23.679201

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5850b285a8b5"
down_revision: Union[str, None] = "b4a089bf66a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("client", "kvk_number", existing_type=sa.VARCHAR(length=256), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("client", "kvk_number", existing_type=sa.VARCHAR(length=256), nullable=False)
    # ### end Alembic commands ###
