"""track form cascade

Revision ID: 59accb0daea9
Revises: 5390a0862f31
Create Date: 2025-05-30 12:08:38.023324

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59accb0daea9"
down_revision: Union[str, None] = "5390a0862f31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("form_track_form_data_Id_fkey", "form_track", type_="foreignkey")
    op.drop_constraint("form_track_track_id_fkey", "form_track", type_="foreignkey")
    op.create_foreign_key("form_track_track_id_fkey", "form_track", "track", ["track_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(
        "form_track_form_data_Id_fkey", "form_track", "form_data", ["form_data_Id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("form_track_track_id_fkey", "form_track", type_="foreignkey")
    op.drop_constraint("form_track_form_data_Id_fkey", "form_track", type_="foreignkey")
    op.create_foreign_key("form_track_track_id_fkey", "form_track", "track", ["track_id"], ["id"])
    op.create_foreign_key("form_track_form_data_Id_fkey", "form_track", "form_data", ["form_data_Id"], ["id"])
    # ### end Alembic commands ###
