"""add bsn to client model

Revision ID: 5c4ac4fb09af
Revises: a16b3ad55edd
Create Date: 2025-05-02 11:35:33.152666

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c4ac4fb09af"
down_revision: Union[str, None] = "a16b3ad55edd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("client", sa.Column("bsn", sa.VARCHAR(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client", "bsn")
    # ### end Alembic commands ###
