"""track status

Revision ID: 5fb3a80273df
Revises: f7bf465f9c2c
Create Date: 2025-05-14 15:37:10.707139

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5fb3a80273df"
down_revision: Union[str, None] = "f7bf465f9c2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("track", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("track", sa.Column("status", sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
