"""refactor form data model

Revision ID: 65b118c12d09
Revises: 36de56afad64
Create Date: 2025-06-19 11:28:50.906817

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "65b118c12d09"
down_revision: Union[str, None] = "36de56afad64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("form_track")
    op.drop_table("form_appointment")
    op.add_column("form_data", sa.Column("track_id", sa.UUID(), nullable=True))
    op.add_column("form_data", sa.Column("appointment_id", sa.UUID(), nullable=True))
    op.create_foreign_key("form_data_track_id_fkey", "form_data", "track", ["track_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(
        "form_data_appointment_id_fkey", "form_data", "appointment", ["appointment_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("form_data_track_id_fkey", "form_data", type_="foreignkey")
    op.drop_constraint("form_data_appointment_id_fkey", "form_data", type_="foreignkey")
    op.drop_column("form_data", "appointment_id")
    op.drop_column("form_data", "track_id")
    op.create_table(
        "form_appointment",
        sa.Column("form_data_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("appointment_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["appointment_id"], ["appointment.id"], name="form_appointment_appointment_id_fkey", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["form_data_id"], ["form_data.id"], name="form_appointment_form_data_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="form_appointment_pkey"),
    )
    op.create_table(
        "form_track",
        sa.Column("track_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("form_data_Id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["form_data_Id"], ["form_data.id"], name="form_track_form_data_Id_fkey", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["track_id"], ["track.id"], name="form_track_track_id_fkey", ondelete="CASCADE"),
    )
    # ### end Alembic commands ###
