"""start/end time not required

Revision ID: 81531f682425
Revises: 9670adff1a42
Create Date: 2025-06-17 11:26:32.453008

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81531f682425"
down_revision: Union[str, None] = "9670adff1a42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("appointment", "start_time", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("appointment", "end_time", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("appointment", "end_time", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.alter_column("appointment", "start_time", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    # ### end Alembic commands ###
