"""track form

Revision ID: 8708826607cd
Revises: 5a03098911b9
Create Date: 2025-05-23 10:58:32.526401

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8708826607cd"
down_revision: Union[str, None] = "5a03098911b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("track", sa.Column("form_data_id", sa.UUID(), nullable=True))
    op.create_foreign_key("track_form_data_id_fkey", "track", "form_data", ["form_data_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("track_form_data_id_fkey", "track", type_="foreignkey")
    op.drop_column("track", "form_data_id")
    # ### end Alembic commands ###
