"""make payload not required

Revision ID: 893c17e04be0
Revises: 42c653a43970
Create Date: 2025-08-13 09:55:28.895291

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "893c17e04be0"
down_revision: Union[str, None] = "42c653a43970"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("form_data", "payload", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("form_data", "payload", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False)
    # ### end Alembic commands ###
