"""make payload not required

Revision ID: 94696d592e85
Revises: 893c17e04be0
Create Date: 2025-08-15 10:37:06.733958

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94696d592e85"
down_revision: Union[str, None] = "893c17e04be0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form_data", sa.Column("payload_unvalidated", sa.JSON(), nullable=True))
    op.add_column("form_data", sa.Column("completed", sa.Boolean(), server_default="false", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_data", "completed")
    op.drop_column("form_data", "payload_unvalidated")
    # ### end Alembic commands ###
