"""form data approval

Revision ID: 94cb9fddb440
Revises: 65b118c12d09
Create Date: 2025-06-19 13:36:41.919334

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94cb9fddb440"
down_revision: Union[str, None] = "65b118c12d09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form_data", sa.Column("approved", sa.Boolean(), nullable=True))
    op.add_column("form_data", sa.Column("last_updated_by_user_id", sa.UUID(), nullable=True))
    op.add_column(
        "form_data",
        sa.Column("approved_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
    )
    op.create_foreign_key(
        "form_data_last_updated_by_user_id_fkey",
        "form_data",
        "user",
        ["last_updated_by_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.execute("update form_data set approved = false")
    op.alter_column(
        table_name="form_data",
        column_name="approved",
        existing_type=sa.Boolean(),
        nullable=False,
        server_default=sa.text("false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("form_data_last_updated_by_user_id_fkey", "form_data", type_="foreignkey")
    op.drop_column("form_data", "approved_at")
    op.drop_column("form_data", "last_updated_by_user_id")
    op.drop_column("form_data", "approved")
    # ### end Alembic commands ###
