"""track approval

Revision ID: a084f7a3c263
Revises: ecec61932f98
Create Date: 2025-05-16 14:09:35.354271

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a084f7a3c263"
down_revision: Union[str, None] = "ecec61932f98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("track", sa.Column("completion_approved", sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("track", "completion_approved")
    # ### end Alembic commands ###
