"""rename track partner to partner organization

Revision ID: a117d2e34265
Revises: bd6f50d5ff4a
Create Date: 2025-06-13 13:13:23.512302

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a117d2e34265"
down_revision: Union[str, None] = "bd6f50d5ff4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "partner_organization",
        sa.Column("name", sa.VARCHAR(length=256), nullable=False),
        sa.Column("email", sa.VARCHAR(length=256), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column("track", sa.Column("partner_organization_id", sa.UUID(), nullable=True))
    op.drop_constraint("track_track_partner_id_fkey", "track", type_="foreignkey")
    op.create_foreign_key(
        "track_partner_organization_id_fkey",
        "track",
        "partner_organization",
        ["partner_organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("track", "track_partner_id")
    op.add_column("user", sa.Column("partner_organization_id", sa.UUID(), nullable=True))
    op.drop_constraint("user_track_partner_id_fkey", "user", type_="foreignkey")
    op.create_foreign_key(
        "user_partner_organization_id_fkey",
        "user",
        "partner_organization",
        ["partner_organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("user", "track_partner_id")
    op.drop_table("track_partner")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.create_table(
        "track_partner",
        sa.Column("name", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("email", sa.VARCHAR(length=256), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="track_partner_pkey"),
        sa.UniqueConstraint(
            "name", name="track_partner_name_key", postgresql_include=[], postgresql_nulls_not_distinct=False
        ),
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("track_partner_id", sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint("user_partner_organization_id_fkey", "user", type_="foreignkey")
    op.create_foreign_key(
        "user_track_partner_id_fkey", "user", "track_partner", ["track_partner_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("user", "partner_organization_id")
    op.add_column("track", sa.Column("track_partner_id", sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint("track_partner_organization_id_fkey", "track", type_="foreignkey")
    op.create_foreign_key(
        "track_track_partner_id_fkey", "track", "track_partner", ["track_partner_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("track", "partner_organization_id")

    op.drop_table("partner_organization")
    # ### end Alembic commands ###
