"""cascade appointment/client

Revision ID: a16b3ad55edd
Revises: ec05c4ea933d
Create Date: 2025-05-02 11:29:43.950920

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a16b3ad55edd"
down_revision: Union[str, None] = "ec05c4ea933d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("appointment_client_id_fkey", "appointment", type_="foreignkey")
    op.drop_constraint("fk_appointment_appointment_type", "appointment", type_="foreignkey")
    op.create_foreign_key(
        "fk_appointment_appointment_type",
        "appointment",
        "appointment_type",
        ["appointment_type_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key("fk_appointment_client", "appointment", "client", ["client_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_appointment_appointment_type", "appointment", type_="foreignkey")
    op.drop_constraint("fk_appointment_client", "appointment", type_="foreignkey")
    op.create_foreign_key(
        "fk_appointment_appointment_type", "appointment", "appointment_type", ["appointment_type_id"], ["id"]
    )
    op.create_foreign_key("appointment_client_id_fkey", "appointment", "client", ["client_id"], ["id"])
    # ### end Alembic commands ###
