"""Fix cascading

Revision ID: a3f456ed9a66
Revises: 333135d3fa60
Create Date: 2025-07-23 15:09:05.903245

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3f456ed9a66"
down_revision: Union[str, None] = "333135d3fa60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("track_partner_organization_id_fkey", "track", type_="foreignkey")
    op.create_foreign_key(
        "track_partner_organization_id_fkey",
        "track",
        "partner_organization",
        ["partner_organization_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("track_partner_organization_id_fkey", "track", type_="foreignkey")
    op.create_foreign_key(
        "track_partner_organization_id_fkey",
        "track",
        "partner_organization",
        ["partner_organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
