"""Do not delete client when user is deleted

Revision ID: a50a17e98c3c
Revises: 94696d592e85
Create Date: 2025-09-04 11:12:54.932682

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a50a17e98c3c"
down_revision: Union[str, None] = "94696d592e85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("case_client_id_fkey", "client", type_="foreignkey")
    op.create_foreign_key("case_client_id_fkey", "client", "user", ["user_id"], ["id"], ondelete="SET NULL")
    op.drop_constraint("file_uploaded_by_user_id_fkey", "file", type_="foreignkey")
    op.create_foreign_key(
        "file_uploaded_by_user_id_fkey", "file", "user", ["uploaded_by_user_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_constraint("fk_user_role", "user", type_="foreignkey")
    op.create_foreign_key("fk_user_role", "user", "role", ["role_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_user_role", "user", type_="foreignkey")
    op.create_foreign_key("fk_user_role", "user", "role", ["role_id"], ["id"], ondelete="SET NULL")
    op.drop_constraint("file_uploaded_by_user_id_fkey", "file", type_="foreignkey")
    op.create_foreign_key(
        "file_uploaded_by_user_id_fkey", "file", "user", ["uploaded_by_user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("case_client_id_fkey", "client", type_="foreignkey")
    op.create_foreign_key("case_client_id_fkey", "client", "user", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###
