"""add partner org to appointment

Revision ID: a6ba1110ba5f
Revises: a117d2e34265
Create Date: 2025-06-13 13:22:32.777640

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6ba1110ba5f"
down_revision: Union[str, None] = "a117d2e34265"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("appointment", sa.Column("partner_organization_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "appointment_partner_organization_id_fkey",
        "appointment",
        "partner_organization",
        ["partner_organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("appointment_partner_organization_id_fkey", "appointment", type_="foreignkey")
    op.drop_column("appointment", "partner_organization_id")
    # ### end Alembic commands ###
