"""rename task table

Revision ID: ab286196d749
Revises: bd3a56506070
Create Date: 2025-07-25 14:10:17.155578

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab286196d749"
down_revision: Union[str, None] = "bd3a56506070"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS taskstatus CASCADE")

    # Explicitly create the enum type (create only if needed)
    taskstatus_enum = postgresql.ENUM("TO_DO", "IN_PROGRESS", "CLOSED", name="taskstatus")
    taskstatus_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "task",
        sa.Column("description", sa.VARCHAR(length=1024), nullable=False),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("TO_DO", "IN_PROGRESS", "CLOSED", name="taskstatus", create_type=False),
            nullable=False,
        ),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("advisor_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["advisor_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["case_id"], ["case.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("case_task")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS taskstatus CASCADE")
    op.create_table(
        "case_task",
        sa.Column("description", sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
        sa.Column("due_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("TO_DO", "IN_PROGRESS", "CLOSED", name="taskstatus"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("case_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("advisor_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["advisor_id"], ["user.id"], name="case_task_advisor_id_fkey", ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["case_id"], ["case.id"], name="case_task_case_id_fkey", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name="case_task_pkey"),
    )
    op.drop_table("task")
    # ### end Alembic commands ###
