"""user active

Revision ID: adf25871999f
Revises: c421c1f165ce
Create Date: 2025-07-30 15:01:46.061583

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "adf25871999f"
down_revision: Union[str, None] = "c421c1f165ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("active", sa.Boolean(), nullable=True))
    op.execute('UPDATE "user" SET active = TRUE')  # Set default value for existing users
    op.alter_column("user", "active", nullable=False)  # Make the column
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "active")
    # ### end Alembic commands ###
