"""track status

Revision ID: afdb8d23866d
Revises: b4a089bf66a9
Create Date: 2025-05-13 16:46:09.267599

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afdb8d23866d"
down_revision: Union[str, None] = "b4a089bf66a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "track",
        sa.Column("status", sa.Enum("Nog niet gestart", "Gestart", "Beëindigd", native_enum=False), nullable=False),
    )
    op.alter_column(
        "track",
        "start_dt",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("track", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "track",
        sa.Column("is_active", sa.BOOLEAN(), server_default=sa.text("true"), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "track",
        "start_dt",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("track", "status")
    # ### end Alembic commands ###
