"""track partner

Revision ID: b4a089bf66a9
Revises: 6780f666bdcf
Create Date: 2025-05-09 10:55:32.642705

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4a089bf66a9"
down_revision: Union[str, None] = "6780f666bdcf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "track_partner",
        sa.Column("name", sa.VARCHAR(length=256), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column("track", sa.Column("track_partner_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "track_track_partner_id_fkey", "track", "track_partner", ["track_partner_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("track_track_partner_id_fkey", "track", type_="foreignkey")
    op.drop_column("track", "track_partner_id")
    op.drop_table("track_partner")
    # ### end Alembic commands ###
