"""track appointment

Revision ID: bcffda693254
Revises: 2a07c7e36e42
Create Date: 2025-06-26 15:17:28.934565

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bcffda693254"
down_revision: Union[str, None] = "2a07c7e36e42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("appointment", sa.Column("track_id", sa.UUID(), nullable=True))
    op.create_foreign_key("fk_appointment_track", "appointment", "track", ["track_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_appointment_track", "appointment", type_="foreignkey")
    op.drop_column("appointment", "track_id")
    # ### end Alembic commands ###
