"""link task to user

Revision ID: bd3a56506070
Revises: d24320439dfb
Create Date: 2025-07-25 13:51:08.929991

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd3a56506070"
down_revision: Union[str, None] = "d24320439dfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("case_task", sa.Column("advisor_id", sa.UUID(), nullable=True))
    op.create_foreign_key("case_task_advisor_id_fkey", "case_task", "user", ["advisor_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("case_task_advisor_id_fkey", "case_task", type_="foreignkey")
    op.drop_column("case_task", "advisor_id")
    # ### end Alembic commands ###
