"""link user to client

Revision ID: bd6f50d5ff4a
Revises: ff0de7ae096d
Create Date: 2025-06-13 10:20:45.350171

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd6f50d5ff4a"
down_revision: Union[str, None] = "ff0de7ae096d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("client", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_foreign_key("case_client_id_fkey", "client", "user", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("case_client_id_fkey", "client", type_="foreignkey")
    op.drop_column("client", "user_id")
    # ### end Alembic commands ###
