"""adjust task

Revision ID: c421c1f165ce
Revises: ab286196d749
Create Date: 2025-07-29 10:23:33.994022

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c421c1f165ce"
down_revision: Union[str, None] = "ab286196d749"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("user_id", sa.UUID(), nullable=True))
    op.add_column("task", sa.Column("completed", sa.Boolean(), nullable=True))
    op.execute("UPDATE task SET completed = false")
    op.alter_column("task", "completed", nullable=False)
    op.drop_constraint("task_advisor_id_fkey", "task", type_="foreignkey")
    op.create_foreign_key("task_user_id_fkey", "task", "user", ["user_id"], ["id"], ondelete="SET NULL")
    op.drop_column("task", "advisor_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("advisor_id", sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint("task_user_id_fkey", "task", type_="foreignkey")
    op.create_foreign_key("task_advisor_id_fkey", "task", "user", ["advisor_id"], ["id"], ondelete="SET NULL")
    op.drop_column("task", "completed")
    op.drop_column("task", "user_id")
    # ### end Alembic commands ###
