"""rename to client

Revision ID: ca72924d10ac
Revises: 50d0c3a0b3f8
Create Date: 2025-04-29 14:46:38.777849

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca72924d10ac"
down_revision: Union[str, None] = "50d0c3a0b3f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("appointment")
    op.add_column("client", sa.Column("initials", sa.VARCHAR(length=256), nullable=False))
    op.add_column("client", sa.Column("last_name_prefix", sa.VARCHAR(length=256), nullable=True))
    op.add_column("client", sa.Column("last_name", sa.VARCHAR(length=256), nullable=False))
    op.add_column("client", sa.Column("company_location", sa.VARCHAR(length=256), nullable=False))
    op.add_column("client", sa.Column("residence_location", sa.VARCHAR(length=256), nullable=False))
    op.add_column("client", sa.Column("company_name", sa.VARCHAR(length=256), nullable=False))
    op.add_column("client", sa.Column("kvk_number", sa.VARCHAR(length=256), nullable=False))
    op.add_column("client", sa.Column("phone_number", sa.VARCHAR(length=256), nullable=False))
    op.add_column("client", sa.Column("agree_to_share_data", sa.Boolean(), nullable=False))
    op.drop_constraint("client_name_key", "client", type_="unique")
    op.drop_column("client", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("client", sa.Column("name", sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.create_unique_constraint("client_name_key", "client", ["name"])
    op.drop_column("client", "agree_to_share_data")
    op.drop_column("client", "phone_number")
    op.drop_column("client", "kvk_number")
    op.drop_column("client", "company_name")
    op.drop_column("client", "residence_location")
    op.drop_column("client", "company_location")
    op.drop_column("client", "last_name")
    op.drop_column("client", "last_name_prefix")
    op.drop_column("client", "initials")
    op.create_table(
        "appointment",
        sa.Column("initials", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("last_name_prefix", sa.VARCHAR(length=256), autoincrement=False, nullable=True),
        sa.Column("last_name", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("company_location", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("residence_location", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("company_name", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("kvk_number", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("phone_number", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("agree_to_share_data", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="appointment_pkey"),
    )
    # ### end Alembic commands ###
