"""Koppel partnerorganisaties aan pijlers

Revision ID: d1c34074ceaf
Revises: 5ae6db78e6d6
Create Date: 2025-10-08 10:22:48.340623

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1c34074ceaf"
down_revision: Union[str, None] = "5ae6db78e6d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("drop table if exists persoon")
    op.add_column("track", sa.Column("product_category_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "track_product_category_key", "track", "product_category", ["product_category_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("track_product_category_key", "track", type_="foreignkey")
    op.drop_column("track", "product_category_id")
    # ### end Alembic commands ###
