"""partner organization product

Revision ID: d24320439dfb
Revises: d790285c312e
Create Date: 2025-07-24 15:42:22.596330

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d24320439dfb"
down_revision: Union[str, None] = "d790285c312e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "partner_organization_product_product_organization_id_fkey", "partner_organization_product", type_="foreignkey"
    )
    op.drop_constraint(
        "partner_organization_product_product_id_fkey", "partner_organization_product", type_="foreignkey"
    )
    op.create_foreign_key(
        "partner_organization_product_product_id_fkey",
        "partner_organization_product",
        "product",
        ["product_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "partner_organization_product_product_organization_id_fkey",
        "partner_organization_product",
        "partner_organization",
        ["product_organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "partner_organization_product_product_organization_id_fkey", "partner_organization_product", type_="foreignkey"
    )
    op.drop_constraint(
        "partner_organization_product_product_id_fkey", "partner_organization_product", type_="foreignkey"
    )
    op.create_foreign_key(
        "partner_organization_product_product_id_fkey",
        "partner_organization_product",
        "product",
        ["product_id"],
        ["id"],
    )
    op.create_foreign_key(
        "partner_organization_product_product_organization_id_fkey",
        "partner_organization_product",
        "partner_organization",
        ["product_organization_id"],
        ["id"],
    )
    # ### end Alembic commands ###
