"""partner organization product

Revision ID: d790285c312e
Revises: 0e105bb5ac65
Create Date: 2025-07-24 14:24:01.389473

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d790285c312e"
down_revision: Union[str, None] = "0e105bb5ac65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "partner_organization_product",
        sa.Column("product_organization_id", sa.UUID(), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_organization_id"],
            ["partner_organization.id"],
        ),
    )
    op.add_column("partner_organization", sa.Column("description", sa.VARCHAR(length=4096), nullable=True))
    op.add_column("partner_organization", sa.Column("description_short", sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("partner_organization", "description_short")
    op.drop_column("partner_organization", "description")
    op.drop_table("partner_organization_product")
    # ### end Alembic commands ###
