"""track partner email

Revision ID: e194aa9a2602
Revises: 525df381c604
Create Date: 2025-06-06 14:50:59.030084

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e194aa9a2602"
down_revision: Union[str, None] = "525df381c604"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("track_partner", sa.Column("email", sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("track_partner", "email")
    # ### end Alembic commands ###
