"""appointment type

Revision ID: ec05c4ea933d
Revises: f3d560227f99
Create Date: 2025-05-02 10:11:49.174172

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec05c4ea933d"
down_revision: Union[str, None] = "f3d560227f99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appointment_type",
        sa.Column("name", sa.VARCHAR(length=256), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column("appointment", sa.Column("appointment_type_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        "fk_appointment_appointment_type", "appointment", "appointment_type", ["appointment_type_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_appointment_appointment_type", "appointment", type_="foreignkey")
    op.drop_column("appointment", "appointment_type_id")
    op.drop_table("appointment_type")
    # ### end Alembic commands ###
