"""user track partner

Revision ID: ecec61932f98
Revises: 017ec9ea2098
Create Date: 2025-05-16 10:28:41.428352

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ecec61932f98"
down_revision: Union[str, None] = "017ec9ea2098"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("track_partner_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "user_track_partner_id_fkey", "user", "track_partner", ["track_partner_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_track_partner_id_fkey", "user", type_="foreignkey")
    op.drop_column("user", "track_partner_id")
    # ### end Alembic commands ###
