"""client email

Revision ID: f59649f21bd1
Revises: ca72924d10ac
Create Date: 2025-04-29 15:01:46.887411

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f59649f21bd1"
down_revision: Union[str, None] = "ca72924d10ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("client", sa.Column("email", sa.VARCHAR(length=256), nullable=False))
    op.add_column("client", sa.Column("email_confirmed", sa.Boolean(), server_default="false", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client", "email_confirmed")
    op.drop_column("client", "email")
    # ### end Alembic commands ###
