"""unique constraint on file

Revision ID: ff0de7ae096d
Revises: 4abc5f8f2444
Create Date: 2025-06-10 14:35:16.726622

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff0de7ae096d"
down_revision: Union[str, None] = "4abc5f8f2444"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_case_filename", "file", ["case_id", "filename"])
    op.create_unique_constraint("uq_track_filename", "file", ["track_id", "filename"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_track_filename", "file", type_="unique")
    op.drop_constraint("uq_case_filename", "file", type_="unique")
    # ### end Alembic commands ###
